name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    permissions :
      id-token : write
      contents : read
      pull-requests : write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set ENV Files based on Branch
        run: |
          echo "VITE_KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "VITE_KAKAO_CLIENT_JS_KEY=${{ secrets.KAKAO_CLIENT_JS_KEY }}" >> .env
          echo "VITE_KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
          echo "VITE_BACKEND_BASE_URL=${{ secrets.BACKEND_BASE_URL }}" >> .env

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK (gcloud CLI)
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/frontend:develop

      - name: Deploy to Compute Engine VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Stopping and removing existing containers..."
            docker stop marong-frontend || true
            docker rm marong-frontend || true

            echo "Authenticating to Artifact Registry..."
            gcloud auth configure-docker asia-northeast3-docker.pkg.dev

            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/frontend:develop

            echo "Starting new container..."
            docker run -d \
              --name marong-frontend \
              -p 80:80 \
              ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/frontend:develop

            echo "Deployment to Compute Engine VM completed."
            
